apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "thirdtask.fullname" . }}
spec:
  minAvailable: {{ .Values.minAvailable }}
  selector:
    matchLabels:
      {{- include "thirdtask.selectorLabels" . | nindent 8 }}
